name: Gilmation Static Website
icon_name: favicon.ico
ga_profile_id: UA-101018981-1
highlighter:
exclude: [ doc, Gemfile, Gemfile.lock, upload_s3.sh, README.md ]
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
  style: compact
url: https://gilmation.com
